# Generated by Django 2.1.8 on 2019-05-05 22:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('image', models.ImageField(null=True, upload_to=posts.models.post_image)),
                ('published', models.BooleanField(default=False, verbose_name='Publicar?')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authors.Author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Category')),
            ],
        ),
    ]
