# Generated by Django 2.1.8 on 2019-05-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
