# Generated by Django 2.1.8 on 2019-05-29 04:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='teser',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authors.Author', verbose_name='Autor'),
        ),
    ]
