# Generated by Django 2.1.8 on 2019-05-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190529_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='teser',
            new_name='pub_date',
        ),
    ]
