# Generated by Django 2.1.8 on 2019-04-15 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
    ]
