# Generated by Django 2.1.8 on 2019-05-29 04:17

import authors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(null=True, upload_to=authors.models.author_image),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
